### PR TITLE
Provide static browser/node targets

### PR DESCRIPTION
**Pull request by TrySound**
Ref https://github.com/uber/react-map-gl/issues/557

In this diff I suggest to migrate from analyzing "dynamic" isBrowser
function in favour of static "browser" router.

This allows webpack to choose the file depending on specified target.

According [this table](https://webpack.js.org/configuration/target/)

web (default) - will consume ./utils/hammer.browser.js
node - will consume ./utils/hammer.js
electron-main - will consume ./utils/hammer.js
electron-renderer - will consume ./utils/hammer.browser.js

I think this even won't be a breaking change.

This will allow to eliminate tricky detections and the last cjs in this
library (except hammer itself) so rollup bundling in user land will
become much easier.

### CODE REVIEW

**Comment by TrySound** [comment]
@ibgreen  @Pessimistress I will send PR with the same trick to react-map-gl if you are okay with it.

**Comment by Pessimistress** [comment]
What does this mean to people not using Webpack or an older version of it?

**Comment by TrySound** [comment]
@Pessimistress I'm sure browser field is used from the beginning.

I just checked. webpack 2, 3, 4 handles this case exactly the same. Webpack 1 didn't have `module` field support so it resolves only main and its browser replacements which is also expected and not breaking.

Rollup will be able to handle this case only after merge (currently I use hacks around it). Parcel supports all these cases from the beginning. Fastpack fixed this issue a few months ago.

**Comment by Pessimistress** [comment]
Published mjolnir.js@2.0.0-alpha.1

**Pull request merged**
