### PR TITLE
Distribute cjs and esm as flat bundles

### PR DESCRIPTION
**Pull request by TrySound**
In this diff I propose to distribute bundles instead of separated files.
There are a few problems I'm trying to solve.

1. Less dependency on commonjs (global.js)
2. Smaller user bundle by deduplicating babel helpers (dist-es6 has
inlined helpers in each file)
3. Faster user bundling
4. Easier debugging without source maps (eval mode) instead of fragmented
and polluted by development bundler like webpack.

### CODE REVIEW

**Comment by TrySound** [comment]
FYI my end goal is reducing `react-map-gl` size.

**Comment by TrySound** [comment]
Here's results I got before and after this PR
```
{
  "bundled": 36479,
  "minified": 15511,
  "gzipped": 4030
}

{
    "bundled": 33614,
    "minified": 13778,
    "gzipped": 3925
}
```

**Comment by TrySound** [comment]
Currently I have to write this custom plugin to bundle mjolnir with rollup. Would be good to get rid at least from `load` hook. Will open separate PR for this.

```js
    {
      name: 'hammerjs-import',
      load(id) {
        if (id.includes('mjolnir.js') && id.includes('globals.js')) {
          return `
            export var userAgent = navigator.userAgent.toLowerCase();
            export var isBrowser = true;
            export {
              window,
              window as global,
              document
            }
          `;
        }
      },
      transform(code, id) {
        if (
          code.includes(`require("hammerjs")`) ||
          code.includes(`require('hammerjs')`)
        ) {
          const importStatement = 'import __hammerjs__ from "hammerjs";\n';
          const processed = code.replace(
            /require\(["']hammerjs["']\)/g,
            '__hammerjs__',
          );
          return {
            code: importStatement + processed,
          };
        }
      },
    },
```

**Comment by ibgreen** [comment]
@TrySound Sorry for slow replies. Thanks for all your great PRs. I'd love to make a joint push with you on reducing react-map-gl's size, it has grown rather too big.

Some comments on your points:

> Smaller user bundle by deduplicating babel helpers (dist-es6 has inlined helpers in each file)

I just landed your #21 that should sort this.

> Less dependency on commonjs (global.js)

Our `global.js` is a tiny file, why is this a big concern?

> Faster user bundling
> Easier debugging without source maps (eval mode) instead of fragmented and polluted by development bundler like webpack.

I like the sound of this, but don't understand enough how this is achieved and the implications.

> Here's results I got before and after this PR

I like the size regression testing. Might want to integrate rollup into our repos just for doing this measurement, even we still keep webpack for most other things for now.

**Pull request closed without merging**
